### ISSUE TITLE
Preview image and social media data

### ISSUE THREAD

**Issue by kaihaase** [lenneTech/academy#103]
The academy should provide appropriate images and information in the meta data.

Currently, a picture of an academy participant is shown, it would be better to have a logo, infographic or other meaningful image.

**Comment by pascal-klesse** [comment]
Facebook:
https://developers.facebook.com/docs/sharing/webmasters/

**Comment by pascal-klesse** [comment]
Twitter:
https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
::Twitter Cards and Open Graph

**Comment by pascal-klesse** [comment]
Summary and Testing:
https://www.kontentino.com/blog/social-media-meta-tags-a-complete-guide/

**Comment by pascal-klesse** [comment]
Check seo meta tags:
https://ahrefs.com/blog/de/seo-meta-tags/

(in Angular we use the SeoService for these settings)
