### ISSUE TITLE
rename ltakademie? 

### ISSUE THREAD

**Issue by DKoenig9** [lenneTech/academy#159]
The name of the page is irritating for some users --> they think the first letter is an uppercase "i" and no lowercase "L". To avoid this mix-up we could think of another name for the academy

We could take the main logo of lenneTech and the name "akademie" so it still would be "lt akademie" but now its visually recognizable.

--> redesigned logo
--> preveiw-images
--> redirection to lenne.Tech

**Comment by RobinZeppenfeld** [comment]
Logo idea has been found and is in progress.
